spring:
  application:
    name: demo1

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:demo1}
    username: ${DB_USER:demo1}
    password: ${DB_PASSWORD:demo1}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET:yAosXNy/vJaEZhwS8ORSed58zQvAwGDP+1tv+Xm9JT4rce+b1IiMc7wShWxgZLIq}
    access-token-ttl: 15m
    refresh-token-ttl: 7d
    issuer: demo1

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  error:
    include-message: always